name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install runtime deps (if present)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          fi

      - name: Install dev deps (pytest etc.)
        run: |
          if [ -f requirements-dev.txt ]; then
            python -m pip install -r requirements-dev.txt
          else
            python -m pip install pytest pytest-cov
          fi

      - name: Run tests
        run: python -m pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=term-missing
