name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install runtime deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install dev/test deps (pytest etc.)
        run: |
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Show installed key packages (debug)
        run: |
          python -c "import sys, pkgutil; print(sys.version)"
          python -c "import importlib; print('pytest:', importlib.import_module('pytest').__version__); print('pytest-cov:', importlib.import_module('pytest_cov').__version__)"

      - name: Run tests
        run: |
          python -m pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=term-missing

      - name: Upload coverage report (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-text
          path: ./.coverage
          if-no-files-found: ignore
